"""
Error Code Enum
Auto-generated from error_codes.yaml
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Standardized error codes for Lyra AI"""
    
    # Model errors
    MODEL_LOAD_FAIL = "MODEL_LOAD_FAIL"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_DOWNLOAD_FAIL = "MODEL_DOWNLOAD_FAIL"
    MODEL_INCOMPATIBLE = "MODEL_INCOMPATIBLE"
    MODEL_NOT_COMPATIBLE = "MODEL_NOT_COMPATIBLE"
    MODEL_REGISTRY_LOAD_FAIL = "MODEL_REGISTRY_LOAD_FAIL"
    
    # Permission errors
    PERMISSION_DENIED = "PERMISSION_DENIED"
    PERMISSION_NOT_GRANTED = "PERMISSION_NOT_GRANTED"
    
    # Resource errors
    LOW_RAM = "LOW_RAM"
    LOW_DISK_SPACE = "LOW_DISK_SPACE"
    GPU_NOT_AVAILABLE = "GPU_NOT_AVAILABLE"
    
    # Network errors
    NETWORK_FAIL = "NETWORK_FAIL"
    DOWNLOAD_TIMEOUT = "DOWNLOAD_TIMEOUT"
    
    # System errors
    WATCHDOG_TIMEOUT = "WATCHDOG_TIMEOUT"
    WORKER_CRASH = "WORKER_CRASH"
    CONFIG_LOAD_FAIL = "CONFIG_LOAD_FAIL"
    CONFIG_INVALID = "CONFIG_INVALID"
    
    # Input validation
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_PARAMETER = "MISSING_PARAMETER"
    
    # Plugin errors
    PLUGIN_LOAD_FAIL = "PLUGIN_LOAD_FAIL"
    PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
    PLUGIN_DISABLED = "PLUGIN_DISABLED"
    
    # Voice pipeline
    STT_FAIL = "STT_FAIL"
    TTS_FAIL = "TTS_FAIL"
    AUDIO_PROCESSING_FAIL = "AUDIO_PROCESSING_FAIL"
    
    # General
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    OPERATION_TIMEOUT = "OPERATION_TIMEOUT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
